language: go

go:
  - '1.14'

before_install:
  - sudo apt-get install libpcap-dev

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

script:
  - go mod download
  - sudo $(which go) test ./... -v -covermode=count -coverprofile=coverage.out
  - cat coverage.out | grep -v "main.go" | grep -v "hosts.go" | grep -v "ports.go" > cover.out
  - goveralls -coverprofile=cover.out -service=travis-ci
  - golangci-lint run

  - export PCAPV=1.9.1
  - wget http://www.tcpdump.org/release/libpcap-$PCAPV.tar.gz
  - tar xvf libpcap-$PCAPV.tar.gz
  - cd libpcap-$PCAPV
  - ./configure --with-pcap=linux
  - make
  - cd ..

  - CGO_ENABLED=1 GOARCH=amd64 GOOS=linux CGO_LDFLAGS+="-L./libpcap-$PCAPV" go build -ldflags="-s -w" -o out/netshark_linux_x86-64 .

  # TODO. MacOS build
  # - GOARCH=amd64 GOOS=darwin go build -o out/netshark_osx .

  - GOARCH=386 GOOS=windows go build -o out/netshark_win32.exe .
  - GOARCH=amd64 GOOS=windows go build -o out/netshark_win64.exe .

deploy:
  provider: releases
  api_key:
    secure: HbzNNuwUQOFAuVPqVmQiUGhshTnkft/x8iNd0UXzGIaLEDUf61AXIPhPCd6tL2fQCuTxQJ1yEYsHeaImQppPsj/0KnFOQ1WeAwnrkR2XzHFVS+2OUHAZqLypbQQJGbhBFVwQopbG4aoRrytFd+bYWVPhAbCLi7lFDlKd8Qq4eQGJqHtpfmEQC0C4YtLHuNm3zQWuu23KgpYu3aFHsBRSCbviwnUYdDO3n3kjrw67rDxz1lBAkUtSpeIlCg4MKh5aPEJdKTsXzTJVQRmgXYjc9kLLRBGwcGiRhN3OZrzAMLzGzibeU2GxcopZK3CVvoKe9YdgBvu1gVy2fQuO7T4G6MECHEAVhDJxRrGKls5CiCcgXVXBcX35LzoxaxN9yzAqC28Rsu+ETc68bNsvVU9atIPIhWeh8VKiNo8HL8Pbj/sntWcRK8XYBNaQnb08EIXU8Qf+wYdRfeOpA8bE15ndsw7TX/9ftupJqLtY6uYMUWY8+AFC6ojCNArzE+x5UBRIJ2c+c6cWo/tBl+QR1vhNw+tLYS6vq85MGzSi2PStRnznc9ZgwCKsPHLmhr/7DsNnVcJpahw1Bdc+q6j/VbaoliDxIHMzUDZ3DYB2LYwDUF+uFANr9ZNymFQPmdLV570yMCW8HgAQtqQz/b7tLP/BvaQ4PekqQ1e1gtZLJdapvoI=
  file_glob: true
  file: out/*
  skip_cleanup: true
  on:
    tags: true
