language: go

go:
  - '1.14'

before_install:
  - sudo apt-get install libpcap-dev tar

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

script:
  - go test ./... -v -covermode=count -coverprofile=coverage.out
  - cat coverage.out | grep -v "main.go" | grep -v "hosts.go" | grep -v "ports.go" > cover.out
  - goveralls -coverprofile=cover.out -service=travis-ci
  - golangci-lint run

  - export PCAPV=1.9.1
  - wget http://www.tcpdump.org/release/libpcap-$PCAPV.tar.gz
  - tar xvf libpcap-$PCAPV.tar.gz

  - cd libpcap-$PCAPV
  - ./configure --with-pcap=linux
  - make
  - cd ..

  - CGO_ENABLED=0 GOARCH=386 GOOS=linux go build --ldflags "-L ./libpcap-$PCAPV -linkmode external -extldflags \"-static\"" -a -o out/netshark_linux_i686 .
  - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build --ldflags "-L ./libpcap-$PCAPV -linkmode external -extldflags \"-static\"" -a -o out/netshark_linux_x86-64 .

  - cd libpcap-$PCAPV
  - ./configure --with-pcap=bpf
  - make
  - cd ..

  - GOARCH=amd64 GOOS=darwin go build --ldflags "-L ./libpcap-$PCAPV -linkmode external -extldflags \"-static\"" -a -o out/netshark_osx .

  - GOARCH=386 GOOS=windows go build -o out/netshark_win32.exe .
  - GOARCH=amd64 GOOS=windows go build -o out/netshark_win64.exe .

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY_SECURE
  file_glob: true
  file: out/*
  skip_cleanup: true
  on:
    tags: true
